# Generated by Django 4.0.2 on 2022-02-10 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_tools_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='article_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='article_brief',
            new_name='brief',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='article_title',
            new_name='title',
        ),
    ]
