# Generated by Django 4.0.2 on 2022-02-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_tools_app', '0003_books_videos_articles_link_alter_articles_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
