# Generated by Django 4.0.2 on 2022-02-10 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dev_tools_app', '0002_rename_article_author_articles_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('brief', models.TextField(blank=True, max_length=250, null=True)),
                ('link', models.TextField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_by', models.TextField(blank=True, max_length=50, null=True)),
                ('date_posted', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('brief', models.TextField(blank=True, max_length=250, null=True)),
                ('link', models.TextField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_by', models.TextField(blank=True, max_length=50, null=True)),
                ('date_posted', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='link',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='brief',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='uploaded_by',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
